config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rock_paper_scissors, only: %i[index]
  post "play", to: "rock_paper_scissors#play"
  root "rock_paper_scissors#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :initialize_context
  protect_from_forgery unless: -> { request.format.json? }

  def initialize_context
    @context = {}
  end
end

app/controllers/rock_paper_scissors_controller.rb
# frozen_string_literal: true

class RockPaperScissorsController < ApplicationController
  def index
    @context[:bets] = RockPaperScissorsService::BETS
  end

  def play
    game_service = RockPaperScissorsService.new(params[:bet])

    game_service.play_game

    @context = {
      result: game_service.result,
      computer_choice: game_service.computer_choice,
      human_choice: game_service.human_choice,
    }

    respond_to do |format|
      format.js { render "result.js.erb" }
      format.json do
        render json: @context
      end
    end
  rescue Errors::BetError
    @context[:error_message] = t("illegal_bet", bet: params[:bet])

    respond_to do |format|
      format.js { render "error.js.erb" }
      format.json do
        render json: @context, status: 400
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RpsGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rock_paper_scissors/_result.html.erb
<div class="modal" id="rps-result-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="close-button d-flex flex-row justify-content-end">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="data d-flex flex-column align-items-center mt-4">
          <% if @context[:result] == RockPaperScissorsService::COMPUTER %>
            <h3 class="text-uppercase rps-result-modal-title"> <%= t('you_lost') %>! </h3>
            <div class="mt-4 rps-result-modal-text"> Curb <%= t('curb_wins', choice: @context[:computer_choice]) %> </div>
          <% elsif @context[:result] == RockPaperScissorsService::HUMAN %>
            <h3 class="text-uppercase rps-result-modal-title"> <%= t('you_win') %>! </h3>
            <div class="mt-4 rps-result-modal-text"> Curb <%= t('curb_lost', choice: @context[:computer_choice]) %> </div>
          <% else %>
            <h3 class="text-uppercase rps-result-modal-title"> <%= t('tie') %>! </h3>
            <div class="mt-4 rps-result-modal-text"> Curb <%= t('tie_threw', choice: @context[:computer_choice]) %> </div>
          <% end %>

          <span class="mt-4 mb-4">
            <%= image_tag "#{@context[:computer_choice]}.svg", class: 'bet-image' %>
          </span>

          <button type="button" class="modal-ok-button mt-4" data-dismiss="modal">
            <span class="modal-ok-button-text">Ok</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rock_paper_scissors/error.js.erb
$('#rps-wait-modal').modal('hide')
$('.wait-modal-bet-span').removeClass('d-flex').addClass('d-none')

alert('<%= j @context[:error_message] %>')

app/views/rock_paper_scissors/index.html.erb
<div id="rock-paper-scissors">
  <div id="content" class="d-flex flex-column justify-content-center align-items-center">
    <h1 class="main-title mt-4"><%= t('main-title') %></h1>

    <div class="description-text mt-4" style="width: 570px">
      <%= t('description-text') %>
    </div>

    <div class="text-uppercase mt-4"><%= t('select-bet-text') %></div>

    <div class="choices d-flex flex-row justify-content-center mt-4">
      <% @context[:bets].each do |bet| %>
        <%= link_to play_path(bet: bet), remote: true, method: :post, 'data-bet' => "#{bet}",
                    class: 'bet-select d-flex flex-column justify-content-center align-items-center' do %>
          <%= image_tag "#{bet}.svg", class: 'bet-image' %>
          <span class="mt-4 bet-text"> <%= t(bet) %> </span>
        <% end %>
      <% end %>
    </div>

    <div class="modal" id="rps-wait-modal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <div class="close-button d-flex flex-row justify-content-end">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="data d-flex flex-column align-items-center mt-4">
              <h3 class="text-uppercase rps-wait-modal-title"> <%= t('waiting') %>! </h3>

              <div class="d-flex flex-row align-items-center">
                <div class="mt-4 mb-4 mr-200">
                  <% @context[:bets].each do |bet| %>
                  <span class="flex-column justify-content-center align-items-center
                               d-none <%= bet %>-span wait-modal-bet-span">
                    <%= image_tag "#{bet}.svg", class: 'bet-image' %>
                  </span>
                  <% end %>
                </div>
                <span>...  </span>
              </div>

              <div class="d-flex flex-row align-items-center mt-4">
                <span class="rps-wait-modal-text your-bet-text"> <%= t('your_bet') %> </span>
                <span class="curb-icon"> <%= image_tag 'curb_logo.png' %> </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="rps-result-area">
  </div>
</div>

app/views/rock_paper_scissors/result.js.erb
$('#rps-result-area').html('<%= j render 'result' %>')

$('.wait-modal-bet-span').removeClass('d-flex').addClass('d-none')
$('#rps-wait-modal').modal('hide')
$('#rps-result-modal').modal('show')